### ISSUE TITLE
Tag format

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SBObjectiveCWrapper#1]
Hi @reesemclean, 

to unify the tag names with other SwiftyBeaver projects, can you please change to the format v0.1.0? Thanks!

**Comment by reesemclean** [comment]
Sure - just for my information, what's the motivation for having v0.1.0 vs 0.1.0?

**Comment by skreutzberger** [comment]
I see the notation with a leading "v" it more often in projects lately. But it may just be personal taste.

**Comment by reesemclean** [comment]
Starting with version 0.1.1 this should be the standard.
