### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SBObjectiveCWrapper#2]
What is the minimum we need to put in the README?

**Comment by reesemclean** [comment]
Mirroring SwiftyBeaver as much as possible:

Description
Requirements
Installation
Usage

I still have an example project to move over and then I'll get on this.

**Comment by skreutzberger** [comment]
Perfect. We need to especially address the most common questions that users do have who are still one foot into Objective C. If possible right in the first paragraph or so.

**Comment by reesemclean** [comment]
I have the first draft up. I was struggling with whether I should assume the user has SwiftyBeaver already setup or if I should go over that as well... I ended up giving a quick example of setting it up — that part could be changed to just point to the SwiftyBeaver readme.
