### ISSUE TITLE
Package Manager Support

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SBObjectiveCWrapper#3]
I saw the projects supports now Carthage, great! I can set up CocoaPods and maybe @davidrothera wants to help with Swift Package Manager.

**Comment by reesemclean** [comment]
I don't know that Swift Package manager makes sense — I think SPM is limited to Swift only? I could be wrong on that.

CocoaPods is setup although it's using tag 0.1.0.

**Comment by skreutzberger** [comment]
you are right, SPM is using Swift :laughing:
