### ISSUE TITLE
Update Cocoapods

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SBObjectiveCWrapper#6]
@reesemclean Can you please push an update to Cocoapods which became necessary due to the latest changes? I just checked and do not have the permission. Thanks!

P.S.: please join the [SwiftyBeaver Slack Channel](https://slack.swiftybeaver.com) - all contributors are there :)

**Comment by reesemclean** [comment]
Version 0.3.0 pushed to CocoaPods.

**Comment by skreutzberger** [comment]
thank you!
