### ISSUE TITLE
Update to Swift 3

### ISSUE THREAD

**Issue by miktap** [SwiftyBeaver/SBObjectiveCWrapper#9]
Any plans to update for Swift 3? Currently the latest SBObjectiveCWrapper is 0.7.0 and that depends on SwiftyBeaver 0.7 which is for Swift 2. SwiftyBeaver 1.0.0 brought the Swift 3 support.

**Comment by skreutzberger** [comment]
@reesemclean Would you like to do it?

**Comment by miktap** [comment]
Good question but unfortunately no :(

**Comment by reesemclean** [comment]
Likely can get it done this weekend. Open to pull requests as well 😀.

**Comment by reesemclean** [comment]
@miktap Just pushed version 1.1.0 for Swift 3 support. Let me know if you see any issues.

**Comment by skreutzberger** [comment]
Thank you @reesemclean - great work 🙌🏆

**Comment by miktap** [comment]
Thanks @reesemclean! Works well!
